### ISSUE TITLE
Cannot pass an array to the template

### ISSUE THREAD

**Issue by ericgrosse** [grit96/gulp-template-html#7]
I'm able to successfully run the following:

```
gulp.task('template', function() {
  gulp.src(config.paths.template)
    .pipe(template(['./src/pages/about/about.html']))
    .pipe(gulp.dest(config.paths.dest + '/testing'));
});
```

However, if I change

`.pipe(template('./src/pages/about/about.html'))`

to

`.pipe(template(['./src/pages/about/about.html']))`

I get the following errors:

```
Error: No template file provided
    at new Templator (C:\...\node_modules\template-html\index.js:18:11)
    at gulpTemplator (C:\...\node_modules\gulp-template-html\index.js:11:19)
    at Gulp.<anonymous> (C:\...\gulpfile.js:67:11)
    at module.exports (C:\...\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (C:\...\node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (C:\...\node_modules\orchestrator\index.js:214:10)
    at Gulp.Orchestrator.start (C:\...\node_modules\orchestrator\index.js:134:8)
    at C:\...\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:129:20
    at nextTickCallbackWith0Args (node.js:453:9)
    at process._tickCallback (node.js:382:13)
```

For this reason, it doesn't seem that I can pipe multiple html files through a single template :/

On a separate note, I find it strange that this package uses the template file as the source and pipes through the html files. I would expect it to be the other way around (a bunch of html files pipe through a single template file).

**Comment by geraintwhite** [comment]
EDIT: GitHub not parsing Markdown in email replies (even after editing) is a [known issue](https://github.com/github/email_reply_parser/issues/25)

The reason you're seeing this issue is because you have the source
files and the template the wrong way round. The following should work as
intended:

``` javascript
gulp.task('template', function() {
  gulp.src(['./src/pages/about/about.html'])
    .pipe(template(config.paths.template))
    .pipe(gulp.dest(config.paths.dest + '/testing'));
});
```

Take a look at [this](https://github.com/grit96/dvbris.co.uk/blob/master/gulpfile.js) for example.

Hopefully this makes sense.

**Comment by geraintwhite** [comment]
Closing as not a problem
